//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormUI.GetMainBelt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetMainBelt.GetMainBeltSoap")]
    public interface GetMainBeltSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetMainBeltInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMainBeltInfo", ReplyAction="*")]
        FormUI.GetMainBelt.GetMainBeltInfoResponse GetMainBeltInfo(FormUI.GetMainBelt.GetMainBeltInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMainBeltInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMainBeltInfo", Namespace="http://tempuri.org/", Order=0)]
        public FormUI.GetMainBelt.GetMainBeltInfoRequestBody Body;
        
        public GetMainBeltInfoRequest() {
        }
        
        public GetMainBeltInfoRequest(FormUI.GetMainBelt.GetMainBeltInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMainBeltInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mainBelt;
        
        public GetMainBeltInfoRequestBody() {
        }
        
        public GetMainBeltInfoRequestBody(int mainBelt) {
            this.mainBelt = mainBelt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMainBeltInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMainBeltInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormUI.GetMainBelt.GetMainBeltInfoResponseBody Body;
        
        public GetMainBeltInfoResponse() {
        }
        
        public GetMainBeltInfoResponse(FormUI.GetMainBelt.GetMainBeltInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMainBeltInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMainBeltInfoResult;
        
        public GetMainBeltInfoResponseBody() {
        }
        
        public GetMainBeltInfoResponseBody(string GetMainBeltInfoResult) {
            this.GetMainBeltInfoResult = GetMainBeltInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetMainBeltSoapChannel : FormUI.GetMainBelt.GetMainBeltSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMainBeltSoapClient : System.ServiceModel.ClientBase<FormUI.GetMainBelt.GetMainBeltSoap>, FormUI.GetMainBelt.GetMainBeltSoap {
        
        public GetMainBeltSoapClient() {
        }
        
        public GetMainBeltSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetMainBeltSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMainBeltSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMainBeltSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormUI.GetMainBelt.GetMainBeltInfoResponse FormUI.GetMainBelt.GetMainBeltSoap.GetMainBeltInfo(FormUI.GetMainBelt.GetMainBeltInfoRequest request) {
            return base.Channel.GetMainBeltInfo(request);
        }
        
        public string GetMainBeltInfo(int mainBelt) {
            FormUI.GetMainBelt.GetMainBeltInfoRequest inValue = new FormUI.GetMainBelt.GetMainBeltInfoRequest();
            inValue.Body = new FormUI.GetMainBelt.GetMainBeltInfoRequestBody();
            inValue.Body.mainBelt = mainBelt;
            FormUI.GetMainBelt.GetMainBeltInfoResponse retVal = ((FormUI.GetMainBelt.GetMainBeltSoap)(this)).GetMainBeltInfo(inValue);
            return retVal.Body.GetMainBeltInfoResult;
        }
    }
}
