//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LabelPrintBusiness
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class LabelPrintEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“LabelPrintEntities”部分中的连接字符串初始化新 LabelPrintEntities 对象。
        /// </summary>
        public LabelPrintEntities() : base("name=LabelPrintEntities", "LabelPrintEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 LabelPrintEntities 对象。
        /// </summary>
        public LabelPrintEntities(string connectionString) : base(connectionString, "LabelPrintEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 LabelPrintEntities 对象。
        /// </summary>
        public LabelPrintEntities(EntityConnection connection) : base(connection, "LabelPrintEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<T_WMS_ITEM> T_WMS_ITEM
        {
            get
            {
                if ((_T_WMS_ITEM == null))
                {
                    _T_WMS_ITEM = base.CreateObjectSet<T_WMS_ITEM>("T_WMS_ITEM");
                }
                return _T_WMS_ITEM;
            }
        }
        private ObjectSet<T_WMS_ITEM> _T_WMS_ITEM;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 T_WMS_ITEM EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToT_WMS_ITEM(T_WMS_ITEM t_WMS_ITEM)
        {
            base.AddObject("T_WMS_ITEM", t_WMS_ITEM);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="T_WMS_ITEM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_WMS_ITEM : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 T_WMS_ITEM 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="dCNO">DCNO 属性的初始值。</param>
        /// <param name="sHIPPER_ID">SHIPPER_ID 属性的初始值。</param>
        /// <param name="iTEMNO">ITEMNO 属性的初始值。</param>
        /// <param name="iTEMNAME">ITEMNAME 属性的初始值。</param>
        /// <param name="sPEC">SPEC 属性的初始值。</param>
        /// <param name="aBCCODE">ABCCODE 属性的初始值。</param>
        /// <param name="iTEMPRICE">ITEMPRICE 属性的初始值。</param>
        /// <param name="sHIPTYPE">SHIPTYPE 属性的初始值。</param>
        /// <param name="iTEMTYPE_ID">ITEMTYPE_ID 属性的初始值。</param>
        /// <param name="pRODUCEAREA">PRODUCEAREA 属性的初始值。</param>
        /// <param name="mANUFACTURER_ID">MANUFACTURER_ID 属性的初始值。</param>
        /// <param name="vENDOR_ID">VENDOR_ID 属性的初始值。</param>
        /// <param name="bASEUOM_ID">BASEUOM_ID 属性的初始值。</param>
        /// <param name="dEFAULTUOM_ID">DEFAULTUOM_ID 属性的初始值。</param>
        /// <param name="sTORAGECONDITION">STORAGECONDITION 属性的初始值。</param>
        /// <param name="iSLOTCTRL">ISLOTCTRL 属性的初始值。</param>
        /// <param name="sHELFLIFE">SHELFLIFE 属性的初始值。</param>
        /// <param name="sHELFLIFETYPE">SHELFLIFETYPE 属性的初始值。</param>
        /// <param name="pALLETRATIO">PALLETRATIO 属性的初始值。</param>
        /// <param name="cREATETIME">CREATETIME 属性的初始值。</param>
        /// <param name="cREATEUSER">CREATEUSER 属性的初始值。</param>
        /// <param name="mODIFYTIME">MODIFYTIME 属性的初始值。</param>
        /// <param name="mODIFYUSER">MODIFYUSER 属性的初始值。</param>
        /// <param name="rOWSTATUS">ROWSTATUS 属性的初始值。</param>
        /// <param name="cATID">CATID 属性的初始值。</param>
        public static T_WMS_ITEM CreateT_WMS_ITEM(global::System.String id, global::System.String dCNO, global::System.Decimal sHIPPER_ID, global::System.String iTEMNO, global::System.String iTEMNAME, global::System.String sPEC, global::System.Decimal aBCCODE, global::System.Decimal iTEMPRICE, global::System.String sHIPTYPE, global::System.String iTEMTYPE_ID, global::System.String pRODUCEAREA, global::System.Decimal mANUFACTURER_ID, global::System.Decimal vENDOR_ID, global::System.Decimal bASEUOM_ID, global::System.Decimal dEFAULTUOM_ID, global::System.Decimal sTORAGECONDITION, global::System.Decimal iSLOTCTRL, global::System.Decimal sHELFLIFE, global::System.String sHELFLIFETYPE, global::System.Int16 pALLETRATIO, global::System.DateTime cREATETIME, global::System.String cREATEUSER, global::System.DateTime mODIFYTIME, global::System.String mODIFYUSER, global::System.Decimal rOWSTATUS, global::System.Decimal cATID)
        {
            T_WMS_ITEM t_WMS_ITEM = new T_WMS_ITEM();
            t_WMS_ITEM.ID = id;
            t_WMS_ITEM.DCNO = dCNO;
            t_WMS_ITEM.SHIPPER_ID = sHIPPER_ID;
            t_WMS_ITEM.ITEMNO = iTEMNO;
            t_WMS_ITEM.ITEMNAME = iTEMNAME;
            t_WMS_ITEM.SPEC = sPEC;
            t_WMS_ITEM.ABCCODE = aBCCODE;
            t_WMS_ITEM.ITEMPRICE = iTEMPRICE;
            t_WMS_ITEM.SHIPTYPE = sHIPTYPE;
            t_WMS_ITEM.ITEMTYPE_ID = iTEMTYPE_ID;
            t_WMS_ITEM.PRODUCEAREA = pRODUCEAREA;
            t_WMS_ITEM.MANUFACTURER_ID = mANUFACTURER_ID;
            t_WMS_ITEM.VENDOR_ID = vENDOR_ID;
            t_WMS_ITEM.BASEUOM_ID = bASEUOM_ID;
            t_WMS_ITEM.DEFAULTUOM_ID = dEFAULTUOM_ID;
            t_WMS_ITEM.STORAGECONDITION = sTORAGECONDITION;
            t_WMS_ITEM.ISLOTCTRL = iSLOTCTRL;
            t_WMS_ITEM.SHELFLIFE = sHELFLIFE;
            t_WMS_ITEM.SHELFLIFETYPE = sHELFLIFETYPE;
            t_WMS_ITEM.PALLETRATIO = pALLETRATIO;
            t_WMS_ITEM.CREATETIME = cREATETIME;
            t_WMS_ITEM.CREATEUSER = cREATEUSER;
            t_WMS_ITEM.MODIFYTIME = mODIFYTIME;
            t_WMS_ITEM.MODIFYUSER = mODIFYUSER;
            t_WMS_ITEM.ROWSTATUS = rOWSTATUS;
            t_WMS_ITEM.CATID = cATID;
            return t_WMS_ITEM;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DCNO
        {
            get
            {
                return _DCNO;
            }
            set
            {
                OnDCNOChanging(value);
                ReportPropertyChanging("DCNO");
                _DCNO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DCNO");
                OnDCNOChanged();
            }
        }
        private global::System.String _DCNO;
        partial void OnDCNOChanging(global::System.String value);
        partial void OnDCNOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SHIPPER_ID
        {
            get
            {
                return _SHIPPER_ID;
            }
            set
            {
                OnSHIPPER_IDChanging(value);
                ReportPropertyChanging("SHIPPER_ID");
                _SHIPPER_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHIPPER_ID");
                OnSHIPPER_IDChanged();
            }
        }
        private global::System.Decimal _SHIPPER_ID;
        partial void OnSHIPPER_IDChanging(global::System.Decimal value);
        partial void OnSHIPPER_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ITEMNO
        {
            get
            {
                return _ITEMNO;
            }
            set
            {
                OnITEMNOChanging(value);
                ReportPropertyChanging("ITEMNO");
                _ITEMNO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ITEMNO");
                OnITEMNOChanged();
            }
        }
        private global::System.String _ITEMNO;
        partial void OnITEMNOChanging(global::System.String value);
        partial void OnITEMNOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ITEMNAME
        {
            get
            {
                return _ITEMNAME;
            }
            set
            {
                OnITEMNAMEChanging(value);
                ReportPropertyChanging("ITEMNAME");
                _ITEMNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ITEMNAME");
                OnITEMNAMEChanged();
            }
        }
        private global::System.String _ITEMNAME;
        partial void OnITEMNAMEChanging(global::System.String value);
        partial void OnITEMNAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHORTNAME
        {
            get
            {
                return _SHORTNAME;
            }
            set
            {
                OnSHORTNAMEChanging(value);
                ReportPropertyChanging("SHORTNAME");
                _SHORTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHORTNAME");
                OnSHORTNAMEChanged();
            }
        }
        private global::System.String _SHORTNAME;
        partial void OnSHORTNAMEChanging(global::System.String value);
        partial void OnSHORTNAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SPEC
        {
            get
            {
                return _SPEC;
            }
            set
            {
                OnSPECChanging(value);
                ReportPropertyChanging("SPEC");
                _SPEC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SPEC");
                OnSPECChanged();
            }
        }
        private global::System.String _SPEC;
        partial void OnSPECChanging(global::System.String value);
        partial void OnSPECChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ABCCODE
        {
            get
            {
                return _ABCCODE;
            }
            set
            {
                OnABCCODEChanging(value);
                ReportPropertyChanging("ABCCODE");
                _ABCCODE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ABCCODE");
                OnABCCODEChanged();
            }
        }
        private global::System.Decimal _ABCCODE;
        partial void OnABCCODEChanging(global::System.Decimal value);
        partial void OnABCCODEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ITEMPRICE
        {
            get
            {
                return _ITEMPRICE;
            }
            set
            {
                OnITEMPRICEChanging(value);
                ReportPropertyChanging("ITEMPRICE");
                _ITEMPRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ITEMPRICE");
                OnITEMPRICEChanged();
            }
        }
        private global::System.Decimal _ITEMPRICE;
        partial void OnITEMPRICEChanging(global::System.Decimal value);
        partial void OnITEMPRICEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SHIPTYPE
        {
            get
            {
                return _SHIPTYPE;
            }
            set
            {
                OnSHIPTYPEChanging(value);
                ReportPropertyChanging("SHIPTYPE");
                _SHIPTYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SHIPTYPE");
                OnSHIPTYPEChanged();
            }
        }
        private global::System.String _SHIPTYPE;
        partial void OnSHIPTYPEChanging(global::System.String value);
        partial void OnSHIPTYPEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ITEMTYPE_ID
        {
            get
            {
                return _ITEMTYPE_ID;
            }
            set
            {
                OnITEMTYPE_IDChanging(value);
                ReportPropertyChanging("ITEMTYPE_ID");
                _ITEMTYPE_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ITEMTYPE_ID");
                OnITEMTYPE_IDChanged();
            }
        }
        private global::System.String _ITEMTYPE_ID;
        partial void OnITEMTYPE_IDChanging(global::System.String value);
        partial void OnITEMTYPE_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PRODUCEAREA
        {
            get
            {
                return _PRODUCEAREA;
            }
            set
            {
                OnPRODUCEAREAChanging(value);
                ReportPropertyChanging("PRODUCEAREA");
                _PRODUCEAREA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PRODUCEAREA");
                OnPRODUCEAREAChanged();
            }
        }
        private global::System.String _PRODUCEAREA;
        partial void OnPRODUCEAREAChanging(global::System.String value);
        partial void OnPRODUCEAREAChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MANUFACTURER_ID
        {
            get
            {
                return _MANUFACTURER_ID;
            }
            set
            {
                OnMANUFACTURER_IDChanging(value);
                ReportPropertyChanging("MANUFACTURER_ID");
                _MANUFACTURER_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MANUFACTURER_ID");
                OnMANUFACTURER_IDChanged();
            }
        }
        private global::System.Decimal _MANUFACTURER_ID;
        partial void OnMANUFACTURER_IDChanging(global::System.Decimal value);
        partial void OnMANUFACTURER_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VENDOR_ID
        {
            get
            {
                return _VENDOR_ID;
            }
            set
            {
                OnVENDOR_IDChanging(value);
                ReportPropertyChanging("VENDOR_ID");
                _VENDOR_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VENDOR_ID");
                OnVENDOR_IDChanged();
            }
        }
        private global::System.Decimal _VENDOR_ID;
        partial void OnVENDOR_IDChanging(global::System.Decimal value);
        partial void OnVENDOR_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BASEUOM_ID
        {
            get
            {
                return _BASEUOM_ID;
            }
            set
            {
                OnBASEUOM_IDChanging(value);
                ReportPropertyChanging("BASEUOM_ID");
                _BASEUOM_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BASEUOM_ID");
                OnBASEUOM_IDChanged();
            }
        }
        private global::System.Decimal _BASEUOM_ID;
        partial void OnBASEUOM_IDChanging(global::System.Decimal value);
        partial void OnBASEUOM_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DEFAULTUOM_ID
        {
            get
            {
                return _DEFAULTUOM_ID;
            }
            set
            {
                OnDEFAULTUOM_IDChanging(value);
                ReportPropertyChanging("DEFAULTUOM_ID");
                _DEFAULTUOM_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULTUOM_ID");
                OnDEFAULTUOM_IDChanged();
            }
        }
        private global::System.Decimal _DEFAULTUOM_ID;
        partial void OnDEFAULTUOM_IDChanging(global::System.Decimal value);
        partial void OnDEFAULTUOM_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal STORAGECONDITION
        {
            get
            {
                return _STORAGECONDITION;
            }
            set
            {
                OnSTORAGECONDITIONChanging(value);
                ReportPropertyChanging("STORAGECONDITION");
                _STORAGECONDITION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STORAGECONDITION");
                OnSTORAGECONDITIONChanged();
            }
        }
        private global::System.Decimal _STORAGECONDITION;
        partial void OnSTORAGECONDITIONChanging(global::System.Decimal value);
        partial void OnSTORAGECONDITIONChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ISLOTCTRL
        {
            get
            {
                return _ISLOTCTRL;
            }
            set
            {
                OnISLOTCTRLChanging(value);
                ReportPropertyChanging("ISLOTCTRL");
                _ISLOTCTRL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISLOTCTRL");
                OnISLOTCTRLChanged();
            }
        }
        private global::System.Decimal _ISLOTCTRL;
        partial void OnISLOTCTRLChanging(global::System.Decimal value);
        partial void OnISLOTCTRLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SHELFLIFE
        {
            get
            {
                return _SHELFLIFE;
            }
            set
            {
                OnSHELFLIFEChanging(value);
                ReportPropertyChanging("SHELFLIFE");
                _SHELFLIFE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHELFLIFE");
                OnSHELFLIFEChanged();
            }
        }
        private global::System.Decimal _SHELFLIFE;
        partial void OnSHELFLIFEChanging(global::System.Decimal value);
        partial void OnSHELFLIFEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SHELFLIFETYPE
        {
            get
            {
                return _SHELFLIFETYPE;
            }
            set
            {
                OnSHELFLIFETYPEChanging(value);
                ReportPropertyChanging("SHELFLIFETYPE");
                _SHELFLIFETYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SHELFLIFETYPE");
                OnSHELFLIFETYPEChanged();
            }
        }
        private global::System.String _SHELFLIFETYPE;
        partial void OnSHELFLIFETYPEChanging(global::System.String value);
        partial void OnSHELFLIFETYPEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 PALLETRATIO
        {
            get
            {
                return _PALLETRATIO;
            }
            set
            {
                OnPALLETRATIOChanging(value);
                ReportPropertyChanging("PALLETRATIO");
                _PALLETRATIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PALLETRATIO");
                OnPALLETRATIOChanged();
            }
        }
        private global::System.Int16 _PALLETRATIO;
        partial void OnPALLETRATIOChanging(global::System.Int16 value);
        partial void OnPALLETRATIOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATETIME
        {
            get
            {
                return _CREATETIME;
            }
            set
            {
                OnCREATETIMEChanging(value);
                ReportPropertyChanging("CREATETIME");
                _CREATETIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATETIME");
                OnCREATETIMEChanged();
            }
        }
        private global::System.DateTime _CREATETIME;
        partial void OnCREATETIMEChanging(global::System.DateTime value);
        partial void OnCREATETIMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEUSER
        {
            get
            {
                return _CREATEUSER;
            }
            set
            {
                OnCREATEUSERChanging(value);
                ReportPropertyChanging("CREATEUSER");
                _CREATEUSER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEUSER");
                OnCREATEUSERChanged();
            }
        }
        private global::System.String _CREATEUSER;
        partial void OnCREATEUSERChanging(global::System.String value);
        partial void OnCREATEUSERChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MODIFYTIME
        {
            get
            {
                return _MODIFYTIME;
            }
            set
            {
                OnMODIFYTIMEChanging(value);
                ReportPropertyChanging("MODIFYTIME");
                _MODIFYTIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MODIFYTIME");
                OnMODIFYTIMEChanged();
            }
        }
        private global::System.DateTime _MODIFYTIME;
        partial void OnMODIFYTIMEChanging(global::System.DateTime value);
        partial void OnMODIFYTIMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MODIFYUSER
        {
            get
            {
                return _MODIFYUSER;
            }
            set
            {
                OnMODIFYUSERChanging(value);
                ReportPropertyChanging("MODIFYUSER");
                _MODIFYUSER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MODIFYUSER");
                OnMODIFYUSERChanged();
            }
        }
        private global::System.String _MODIFYUSER;
        partial void OnMODIFYUSERChanging(global::System.String value);
        partial void OnMODIFYUSERChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ROWSTATUS
        {
            get
            {
                return _ROWSTATUS;
            }
            set
            {
                OnROWSTATUSChanging(value);
                ReportPropertyChanging("ROWSTATUS");
                _ROWSTATUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROWSTATUS");
                OnROWSTATUSChanged();
            }
        }
        private global::System.Decimal _ROWSTATUS;
        partial void OnROWSTATUSChanging(global::System.Decimal value);
        partial void OnROWSTATUSChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CATID
        {
            get
            {
                return _CATID;
            }
            set
            {
                OnCATIDChanging(value);
                ReportPropertyChanging("CATID");
                _CATID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CATID");
                OnCATIDChanged();
            }
        }
        private global::System.Decimal _CATID;
        partial void OnCATIDChanging(global::System.Decimal value);
        partial void OnCATIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BIGBOX_BAR
        {
            get
            {
                return _BIGBOX_BAR;
            }
            set
            {
                OnBIGBOX_BARChanging(value);
                ReportPropertyChanging("BIGBOX_BAR");
                _BIGBOX_BAR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BIGBOX_BAR");
                OnBIGBOX_BARChanged();
            }
        }
        private global::System.String _BIGBOX_BAR;
        partial void OnBIGBOX_BARChanging(global::System.String value);
        partial void OnBIGBOX_BARChanged();

        #endregion

    
    }

    #endregion

    
}
