//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormUI.Billservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.ztel.com/", ConfigurationName="Billservice.WMSBillServiceInterface")]
    public interface WMSBillServiceInterface {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        FormUI.Billservice.BillScanResponse BillScan(FormUI.Billservice.BillScan request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillScan {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BillScan", Namespace="http://webservice.ztel.com/", Order=0)]
        public FormUI.Billservice.BillScanBody Body;
        
        public BillScan() {
        }
        
        public BillScan(FormUI.Billservice.BillScanBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class BillScanBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public BillScanBody() {
        }
        
        public BillScanBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillScanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BillScanResponse", Namespace="http://webservice.ztel.com/", Order=0)]
        public FormUI.Billservice.BillScanResponseBody Body;
        
        public BillScanResponse() {
        }
        
        public BillScanResponse(FormUI.Billservice.BillScanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class BillScanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public BillScanResponseBody() {
        }
        
        public BillScanResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WMSBillServiceInterfaceChannel : FormUI.Billservice.WMSBillServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WMSBillServiceInterfaceClient : System.ServiceModel.ClientBase<FormUI.Billservice.WMSBillServiceInterface>, FormUI.Billservice.WMSBillServiceInterface {
        
        public WMSBillServiceInterfaceClient() {
        }
        
        public WMSBillServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WMSBillServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSBillServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSBillServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormUI.Billservice.BillScanResponse FormUI.Billservice.WMSBillServiceInterface.BillScan(FormUI.Billservice.BillScan request) {
            return base.Channel.BillScan(request);
        }
        
        public string BillScan(string arg0) {
            FormUI.Billservice.BillScan inValue = new FormUI.Billservice.BillScan();
            inValue.Body = new FormUI.Billservice.BillScanBody();
            inValue.Body.arg0 = arg0;
            FormUI.Billservice.BillScanResponse retVal = ((FormUI.Billservice.WMSBillServiceInterface)(this)).BillScan(inValue);
            return retVal.Body.@return;
        }
    }
}
